### ISSUE TITLE
The required anti-forgery cookie "__RequestVerificationToken" is not present.

### ISSUE THREAD

**Issue by mjenadi** [Eph-It/RemoteConnectionCenter#1]
Hello,

I tried the process with 2 different admin account but i have the same issue when i click in save in the portal settings : 

Server Error in '/' Application.

The required anti-forgery cookie "__RequestVerificationToken" is not present.

![CM-RDP](https://user-images.githubusercontent.com/62653277/77899145-92a4b380-727c-11ea-9bb2-5d4f6fac20af.PNG)

Do you know this issue please?

Thank you in advance

**Comment by Ryan2065** [comment]
Sorry - been out for awhile to take care of my wife.

This looks like IE, is it IE enhanced security mode?  I had to do a little bit of javascript to get the cookie working and wondering if IE enhanced security mode disables that javascript.

**Comment by mjenadi** [comment]
Hi Rayan, 
Its ok now when i disable IE Enhanced Security mode.

Thank you
